// Copyright Epic Games, Inc. All Rights Reserved.
#include "K2_AdvancedTimelinePinFactory.h"
#include "Widgets/DeclarativeSyntaxSupport.h"
#include "SAdvancedTimelinePinWidget.h"
#include "EdGraphSchema_K2.h"
#include "SGraphPin.h"
#include "K2Node_AddTrack.h"


TSharedPtr<SGraphPin> FK2AdvancedTimelinePinFactory::CreatePin(UEdGraphPin* InPin) const
{
	//如果是FName
	if (InPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Name)
	{
		UObject* Outer = InPin->GetOuter();

		//拿到引脚对应的Class
		if (Outer->IsA(UK2Node_AddTrack::StaticClass()))
		{
			////判断是否是需要的节点
			//UK2Node_AddTrack* AddTrackNode = CastChecked<UK2Node_AddTrack>(Outer);
			////拿到指定的引脚
			//UEdGraphPin* ArrayPin;
			//if (ArrayPin)
			//{
			//	//如果拿到的引脚存在，并且是指定的类型，就使用指定的参数重新创建那个引脚
			//	if (ArrayPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Object || ArrayPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Struct)
			//	{
			//		TArray<FString> PropertyNames;
			//		//返回了一个继承自SGraphPinNameList的自定义下拉列表Widget。这个自定义的下拉列表Widget内容会根据传入的第三个参数来决定。
			//		return SNew(SAdvancedTimelinePinWidget, AddTrackNode, PropertyNames);
			//	}
			//	else
			//	{//如果不存在那个引脚，就根据类型创建基本的默认值
			//		UEdGraphPin* PropertyNamePin;
			//		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(PropertyNamePin);
			//	}
			//}
		}
	}
	return nullptr;
}
